---
version: "2.0"
services:
  app:
    image: dimokus88/automatic1111:0.1.20
    expose:
      - port: 8080
        as: 8080
        to:
          - global: true
    env:
      - "MODEL_LINK=" # if left blank, the model version 1.5 will be loaded. For example, for model version 2.1, link https://huggingface.co/stabilityai/stable-diffusion-2-1/resolve/main/v2-1_768-ema-pruned.ckpt
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 6.0
        memory:
          size: 20Gi
        gpu:
          units: 1
        storage:
          size: 30Gi
  placement:
    akash:       
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
